"LR": 0.0005
"NUM_ENVS": 128
"NUM_STEPS": 1000
"TOTAL_TIMESTEPS": 1e8
"UPDATE_EPOCHS": 2
"NUM_MINIBATCHES": 500
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"ENV_NAME": "clean_up"
"REW_SHAPING_HORIZON": 2.5e6 # for how many timesteps add a shaping reward
"SHAPING_BEGIN": 1e6
"ANNEAL_LR": True
"SEED": 0
"NUM_SEEDS": 1
"TUNE": False

"ENV_KWARGS": 
  "num_agents" : 7          # 1 innovator + 6 imitators (match other conditions)
  "num_inner_steps" : 1000
  "shared_rewards" : False
  "cnn" : True
  "jit" : True

"NICENESS_DECAY": 0.95
"IMITATOR_LAMBDA": 0.2
"INNOVATOR_INDEX": 0
"PARAMETER_SHARING": True  # keep a shared imitator policy (separate innovator policy)
"GIF_NUM_FRAMES": 250

# WandB Params
"ENTITY": ""
"PROJECT": "socialjax-cleanup"
"WANDB_MODE" : "online"
"WANDB_TAGS":
  - RECIPROCITY
"CONDITION": "C4"
"MECHANISM_CLASS": "ClassIV"
"ALGO_NAME": "IPPO-Reciprocity"
"RUN_NAME": ""
